trigger:
- main

pool:
  name: Vijay-Macbook
  demands:
  - Agent.Name -equals VijayMacbook

steps:
- script: echo "Hello from Self-Hosted Mac Agent"
  displayName: 'Hello World'

- script: hostname
  displayName: 'Check Hostname'
